# Generated by Django 5.2.5 on 2025-09-13 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
